공지사항 페이지네이션 적용
kotlin-project-team/backend pull request #35
Opened 2023-11-26 10:17 UTC by yubin21

### 구현한 기능 및 설명 🔨
* 공지사항의 조회 기능에 페이지네이션을 적용하였습니다.

### 발생한 오류 및 해결 방법 🔑
* api 관련 에러는 아니지만 local DB에 문제가 있어, 이를 해결하는 데에 시간을 많이 소모했습니다.

2023-11-26 11:32 UTC, JaeHyeonSim commented
이번주도 수고하셨습니다!

2023-11-26 12:18 UTC, JaeHyeonSim approved these changes

2023-11-26 12:18 UTC, JaeHyeonSim commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/dto/request/NoticeCreateRequest.kt
> +) {
이제 notice의 차례군요.. 저도 분발하겠습니다,,
[질문] 내용물(?)이 같은데 create request와 update request를 나누신 이유가 궁금합니다!

2023-11-26 12:27 UTC, yu-heejin requested changes
고생하셨어요!

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/controller/NoticeController.kt
> +    fun createnotice(
[필수] 캐멀 케이스로 수정하심 좋을 것 같습니다!

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/controller/NoticeController.kt
> +        @RequestBody noticeUpdateRequest: NoticeUpdateRequest,
[선택] 이 부분은 따로 유효성 검사를 하지 않아도 괜찮을까요?

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/controller/NoticeController.kt
> +        return try {
이 부분 나중에 globalException으로 빼실 계획이신가요?

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/controller/NoticeController.kt
> +        return ResponseEntity.ok().build()
[필수] 위에 BaseResponse로 응답하고 있으니 이 부분은 지워도 괜찮을 것 같네요!

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/dto/request/NoticeCreateRequest.kt
> +) {
[선택] 이 부분 괄호`({})`는 없어도 괜찮을 것 같아요!

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/repository/NoticeRepository.kt
> +}
[선택] 여기도 괄호 없어도 괜찮을 것 같군뇽

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/service/NoticeService.kt
> +class NoticeService(private val noticeRepository: NoticeRepository, private val noticeQueryDslRepository: NoticeQueryDslRepository,) {
```suggestion
class NoticeService(private val noticeRepository: NoticeRepository, private val noticeQueryDslRepository: NoticeQueryDslRepository) {
```
,는 없어도 괜찮을 것 같아요~

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/service/NoticeService.kt
> +class NoticeService(private val noticeRepository: NoticeRepository, private val noticeQueryDslRepository: NoticeQueryDslRepository,) {
[선택] 추가로 printWidth가 120줄이 넘을 것 같은데 이 부분도 고려해주세요!

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/service/NoticeService.kt
> +        noticeRepository.save(notice)
```suggestion
        return noticeRepository.save(notice).id
```

[선택] 이렇게 하시면 코드 좀 짧게 줄일 수 있을 것 같아요~!

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/service/NoticeService.kt
> +        val notice = noticeRepository.findById(noticeId).get()
이 부분 optional 관련 오류는 따로 없나요?

2023-11-26 12:27 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/service/NoticeService.kt
> +            noticeRepository.deleteById(notice.id!!)
[선택] `orElseThrow()` 혹은 `findByIdOrNull`을 사용해보시면 더 좋을 것 같아요!

2023-11-26 12:33 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/dto/request/NoticeCreateRequest.kt
> +) {
요부분은 합쳐도 될 것 같습니다! 다음 커밋에서 반영하겠습니다

2023-11-26 12:33 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/controller/NoticeController.kt
> +        return try {
그렇게 생각하고 있습니다!

2023-11-26 12:33 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/controller/NoticeController.kt
> +    fun createnotice(
오 저런 실수를 했군요..! 죄송합니다 바로 반영하겠습니다

2023-11-26 12:33 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/dto/request/NoticeCreateRequest.kt
> +) {
음 이부분은 수정하다가 실수한 것 같습니다 중괄호는 삭제할게요!

2023-11-30 00:57 UTC, yu-heejin approved these changes
고생하셨습니다^_^

2023-11-30 13:13 UTC, merged