Feature/comment
kotlin-project-team/backend pull request #43
Opened 2023-12-31 11:52 UTC by yubin21

### 구현한 기능 및 설명 🔨
* Sllice 에서 필요한 정보만 parsing 하여 표기하도록 변경하였습니다.

2023-12-31 12:16 UTC, yu-heejin requested changes
고생하셨습니다!

2023-12-31 12:16 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/controller/CommentController.kt
> +@RequestMapping("/api")
`"api/post/{post-id}/comment/{comment-id}"` 이런식으로 고정해 놓으면 편하지 않을까요?

2023-12-31 12:16 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/dto/response/CommentResponse.kt
> +    val id: Long?,
잘 몰라서 여쭤보는건데 이 부분 nullable로 하신 이유가 있으신가요?

2023-12-31 12:16 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/repository/CommentQueryDslRepository.kt
> +//
필요 없는 코드는 지워주세요!

2023-12-31 12:16 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/repository/CommentQueryDslRepository.kt
> +        val commentResponses = results.map { comment ->
이러한 비즈니스 로직은 repository 말고 service로 옮겨주세요!

2023-12-31 12:16 UTC, yu-heejin commented on src/main/resources/application.yml
> +        ddl-auto: create # none
이 부분은.. pull 한 번만 받아주세요 :)

2023-12-31 12:22 UTC, JaeHyeonSim commented
이번 주도 고생하셨습니다!

2023-12-31 13:04 UTC, JaeHyeonSim approved these changes

2023-12-31 13:04 UTC, JaeHyeonSim commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/controller/CommentController.kt
> +    fun getAllComment(@RequestParam lastCommentId: Long, pageable: Pageable): ResponseEntity<Slice<Comment>> {
더 직관적인 이름으로 바뀌었네요!!

2024-01-08 11:12 UTC, yu-heejin requested changes

2024-01-08 11:12 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/entity/Comment.kt
>      @Column(name = "user_id", nullable = false)
user, post 부분 엔티티가 모두 올라와있으니 다음주 PR엔 연관 관계 매핑 같이 해주세요 :)

2024-01-08 11:12 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/repository/CommentQueryDslRepository.kt
> +    fun searchCommentsBySlice(lastCommentId: Long, pageable: Pageable): List<Comment> {
중요한건 아닌데 아래처럼 코드를 작성하실 수도 있습니당
```
fun searchCommentsBySlice(lastCommentId: Long, pageable: Pageable): List<Comment> = queryDslFactory.selectFrom(qComment)
            .where(
                qComment.isDeleted.eq(false)
                qComment.isDeleted.eq(false),
                qComment.id.gt(lastCommentId)
            )
            .orderBy(qComment.id.desc())
            .orderBy(qComment.id.asc())
            .limit((pageable.pageSize + 1).toLong())
```

2024-01-08 11:12 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/service/CommentService.kt
> +    val commentQueryDslRepository: CommentQueryDslRepository,
```suggestion
   private val commentQueryDslRepository: CommentQueryDslRepository,
```

2024-01-08 11:12 UTC, yu-heejin commented on src/main/resources/application.yml
> +        ddl-auto: create # none
여기 수정이 안됐어요!

2024-01-08 11:55 UTC, yubin21 commented on src/main/resources/application.yml
> +        ddl-auto: create # none
pull 받아도 수정이 안된 상태인거 같습니다(그때 보여드린 서브모듈과 연관이 있는거 같기도 하네요..) 그냥 제가 수정하여 올리겠습니다!

2024-01-08 14:10 UTC, yu-heejin approved these changes
고생하셨습니다~! 다음주까지는 연관관계 매핑, private 변경 등 이번주 리뷰에 있던거 반영해주세요.

2024-01-08 14:12 UTC, merged