공지사항 조회 수정
kotlin-project-team/backend pull request #44
Opened 2023-12-31 11:55 UTC by yubin21

### 구현한 기능 및 설명 🔨
* title 과 category를 추가하였습니다. 
* 공지사항 조회시 해당 카테고리에 맞는 글만 조회되도록 수정하였습니다.

2023-12-31 12:23 UTC, yu-heejin requested changes

2023-12-31 12:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/controller/NoticeController.kt
> +        @ValidateCategory(enumClass = BoardCategoryType::class) category: BoardCategoryType,
[필수] 여기 BoardCategory 말고 공지할 땐 다른 카테고리를 쓰는 것이 좋지 않을까요?

2023-12-31 12:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/dto/request/NoticeCreateRequest.kt
> +    var category: BoardCategoryType
[필수] 위에 수정되면 이 부분도 수정되어야 할 것 같아요!

2023-12-31 12:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/entity/Notice.kt
> +    var id: Long?,
[선택] @Id 필드는 중요한건 아니지만 맨 밑으로 가면 좋습니당
https://multifrontgarden.tistory.com/304

2023-12-31 12:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/repository/NoticeQueryDslRepository.kt
> +            .where(qNotice.isDeleted.eq(false) .and(qNotice.category.eq(categoryType)) )
[필수] .and 위치 아래로 내려야할 것 같습니다.

2023-12-31 13:15 UTC, JaeHyeonSim approved these changes

2023-12-31 13:15 UTC, JaeHyeonSim commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/dto/response/NoticeCategoryFreeResponse.kt
> +    val title: String,
title이 추가되었군요! 감사합니다!

2023-12-31 13:15 UTC, JaeHyeonSim commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/entity/Notice.kt
> +    var title: String?,
[질문(?)] 왠지.. var val 이 혼용되고 있습니다..!

2024-01-05 08:19 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/repository/NoticeQueryDslRepository.kt
> +            .where(qNotice.isDeleted.eq(false) .and(qNotice.category.eq(categoryType)) )
확인했습니다! 수정해두도록 할게요!

2024-01-08 11:28 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/entity/Notice.kt
> +    var title: String?,
title은 수정이 가능해서 var로 처리하였습니다! 그외에 문제되는 부분이 있을까요?

2024-01-08 11:29 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/notice/repository/NoticeQueryDslRepository.kt
> +            .where(qNotice.isDeleted.eq(false) .and(qNotice.category.eq(categoryType)) )
카테고리 삭제하며 관련 내용도 삭제하였습니다!

2024-01-08 14:16 UTC, yu-heejin approved these changes
고생하셨습니다! querydslRepository에서 이름이 findAllPost인지는 궁금하긴 하네요 🤨

2024-01-08 14:18 UTC, merged