댓글 생성/수정/조회 기능
kotlin-project-team/backend pull request #9
Opened 2023-09-12 04:18 UTC by yubin21

### 구현한 기능 및 설명 🔨
* 댓글 CRUD (delete 오류 수정중)
*

### 발생한 오류 및 해결 방법 🔑
* hard delete 과정 중 comment 가 db에서 정상적으로 삭제되지 않는 문제가 있어, 추후 soft delete로 변경함과 동시에 정상적으로 처리되도록 변경하겠습니다.
* report 에서 erd 잘못 이해한 부분이 있어 추후 다시 진행하겠습니다.

2023-09-12 09:19 UTC, JaeHyeonSim commented
확인했습니다. report도 파이팅! (저부터 해야되지만)

2023-09-13 03:32 UTC, yu-heejin requested changes
고생하셨습니다! 추후 주석은 지워주세요!

2023-09-13 03:32 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/controller/CommentController.kt
> +    ): ResponseEntity<BaseResponse> {
리턴타입이 Unit 아닐까요?

2023-09-13 03:32 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/dto/response/CommentReportResponse.kt
> +    val is_solved: Boolean
캐멀 케이스로 수정해주세요~

2023-09-13 03:32 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/entity/Comment.kt
>  @AllArgsConstructor
AllArgs가 필요한 경우가 있나요? 어떤 데이터가 들어가야할지 고민해보시고 생성자를 만드는 것이 좋을 것 같습니다!

2023-09-13 03:32 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/entity/Comment.kt
> +    @ColumnDefault("false")
이 경우 @DynamicInsert도 같이 사용해야할 거예요

2023-09-13 03:32 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/service/CommentService.kt
> +        return commentRepository.save(comment)
create라 return할 필요는 없을 것 같아요!

2023-09-13 03:32 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/common/config/BaseResponse.kt
> +    val status: String,
responseData도 필요하지 않을까요?

2023-09-13 03:32 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/controller/CommentController.kt
> +    fun deleteComment(@PathVariable commentId: Long): ResponseEntity<BaseResponse> {
여기도 ResponseEntity<Unit> 같아요!

2023-09-14 06:38 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/entity/Comment.kt
> +    @ColumnDefault("false")
수정했습니다! JPA에 대한 이해가 부족했네요 감사해요!

2023-09-14 06:41 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/common/config/BaseResponse.kt
> +    val status: String,
responseData기 필요한 이유를 자세히 알 수 있을까요? 명세서의 body값에는 code, status만 reutrn 하는 것으로 되어 있어 base를 저렇게 작성했습니다.

2023-09-14 06:42 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/service/CommentService.kt
> +        return commentRepository.save(comment)
이전에 baseResponse로 수정하던 중 return을 제외하지 않은 것 같네요 수정하겠습니다!

2023-09-14 06:47 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/dto/response/CommentReportResponse.kt
> +    val is_solved: Boolean
ERD를 보고 작성해서 수정하는 것을 잊었네요..! 수정하겠습니다!

2023-09-14 06:52 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/service/CommentService.kt
> +        return commentRepository.save(comment)
result의 결과로 return 받아야 최종적으로 URI 생성이 가능(result.id)해서 이대로 return 하는 것이 맞지 않을까요?

2023-09-14 06:52 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/entity/Comment.kt
>  @AllArgsConstructor
AllArgs 사용에 대해 다시 고민해보겠습니다. 감사합니다!

2023-09-14 07:31 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/common/config/BaseResponse.kt
> +    val status: String,
명세서 자세히 보시면 data도 있어요~

2023-09-14 07:31 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/service/CommentService.kt
> +        return commentRepository.save(comment)
https://github.com/woowacourse-teams/2020-6rinkers/blob/dev/back/cocktailpick-api/src/main/java/com/cocktailpick/api/cocktail/controller/CocktailController.java 해당 코드 참조해보세요~

2023-09-17 04:23 UTC, yu-heejin requested changes
불필요한 괄호나 공백도 같이 수정해주세요!

2023-09-17 04:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/common/config/BaseResponse.kt
> +    val status: String
data는 없는건가요!

2023-09-17 04:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/common/config/ResponseStatus.kt
> +    // comment status
주석은 지워도 될 것 같습니다!

2023-09-17 04:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/controller/CommentController.kt
> +    ): ResponseEntity<CommentReportResponse> {
요기 응답형태가 갑자기 바뀌었네요..?! CommentReportResponse로 설정하신 이유가 있나요?

2023-09-17 04:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/controller/CommentController.kt
> +    ): ResponseEntity<Void> {
Void 말고 Unit으로 바꿔주세요~

2023-09-17 04:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/controller/CommentController.kt
> +        return ResponseEntity.status(result.code).body(result)
다른 코드에서 ok(), created()와 같은 방식이 사용되었는데 여기만 다르네요! 코드 일관성 생각하셔서 통일해주시면 더 좋을 것 같아요.

2023-09-17 04:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/entity/ReportComment.kt
> +@Table(name = "commentReport")
테이블 명은 스네이크케이스입니다!

2023-09-17 04:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/service/CommentService.kt
> +        val reportComment = ReportComment(commentReportRequest.reason, commentReportRequest.isSolved)
여기 순환참조 되어있는데 어떻게 된 일인가요..!

2023-09-17 04:23 UTC, yu-heejin commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/service/CommentService.kt
> +        BaseResponse(ResponseStatus.SUCCESS)
BaseResponse같은 경우는 불필요한 코드 같아요~

2023-09-17 06:48 UTC, yubin21 commented on src/main/kotlin/com/kotlin/study/dongambackend/domain/comment/controller/CommentController.kt
> +    ): ResponseEntity<CommentReportResponse> {
api report 명세에 있던 형태로 response 하고자 변경하였습니다!

2023-09-17 12:44 UTC, JaeHyeonSim approved these changes

2023-09-24 09:56 UTC, yu-heejin approved these changes

2023-09-24 09:56 UTC, merged